/**
 * Validates public assets and regenerates sequence metadata before build.
 * Run via: npm run sync-assets (also runs as prebuild)
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function syncSequenceManifest() {
  const seqDir = path.join(root, "public", "sequence");
  if (!fs.existsSync(seqDir)) {
    console.warn("[sync-assets] public/sequence missing — skipping");
    return;
  }

  const frames = fs
    .readdirSync(seqDir)
    .filter((f) => /^frame_\d{3}\.webp$/i.test(f))
    .sort((a, b) => a.localeCompare(b));

  if (frames.length === 0) {
    throw new Error("[sync-assets] No frame_XXX.webp files in public/sequence");
  }

  const indices = frames.map((f) => parseInt(f.match(/(\d{3})/)[1], 10));
  const expected = Array.from({ length: frames.length }, (_, i) => i);
  const gaps = expected.filter((i) => !indices.includes(i));

  if (gaps.length > 0) {
    console.warn(
      `[sync-assets] Sequence gap warning: missing indices (first 10): ${gaps.slice(0, 10).join(", ")}`
    );
  }

  const outPath = path.join(root, "src/lib/sequence/generated.ts");
  const content = `// Auto-generated by scripts/sync-assets.mjs — do not edit manually
export const FRAME_COUNT = ${frames.length};
`;

  fs.writeFileSync(outPath, content, "utf8");
  console.log(`[sync-assets] Sequence: ${frames.length} frames → generated.ts`);
}

function validateProjectImages() {
  const projectsRoot = path.join(root, "public", "images", "projects");
  if (!fs.existsSync(projectsRoot)) return;

  let fileCount = 0;
  let totalMb = 0;
  const categories = [];

  for (const entry of fs.readdirSync(projectsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
    if (/-\d{8}T\d{6}Z-/i.test(entry.name)) continue;
    categories.push(entry.name);
  }

  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith(".")) walk(abs);
        continue;
      }
      if (entry.name === ".gitkeep") continue;
      const stat = fs.statSync(abs);
      fileCount++;
      totalMb += stat.size;
    }
  };

  walk(projectsRoot);
  console.log(
    `[sync-assets] Categories: ${categories.length} (${categories.join(", ")})`
  );
  console.log(
    `[sync-assets] Media files: ${fileCount}, ${(totalMb / 1024 / 1024).toFixed(1)} MB`
  );
}

syncSequenceManifest();
validateProjectImages();
